print("Welcome to the band name generator ")
name=input("what's the name of the city you grew up in?\n")
pet=input("what's your pet's name?\n")
print("your band name could be "+name+" "+pet)
len(name)
len(pet)
